export const productData = [
    {
        productName: "Margherita Pizza small",
        productVisibility: "Catalog",
        unit: "m",
        sellingPrice: "1000",
        purchasePrice: "800",
        vatSale: "Export/Befreit (0 %)",
        vatPurchase: "Normalsatz (8.1 %)",
        sku: "11",
        barcode: "123",
        stock: "1",
        description: "This is a test product description."
    },
    {
        productName: "Pepperoni Pizza normal",
        productVisibility: "Search",
        unit: "ml",
        sellingPrice: "1100",
        purchasePrice: "900",
        vatSale: "Reduzierter Satz (2.6 %)",
        vatPurchase: "Export/Befreit (0 %)",
        sku: "16",
        barcode: "156",
        stock: "2",
        description: "This is a test product description 2."
    },
    {
        productName: "Cheeseburger big",
        productVisibility: "Catalog",
        unit: "mm",
        sellingPrice: "1200",
        purchasePrice: "1000",
        vatSale: "Sondersatz (3.8 %)",
        vatPurchase: "Sondersatz (3.8 %)",
        sku: "345",
        barcode: "196",
        stock: "9",
        description: "This is a test product description 3."
    },
    {
        productName: "Veggie Burger",
        productVisibility: "Search",
        unit: "Stk",
        sellingPrice: "1300",
        purchasePrice: "1100",
        vatSale: "Normalsatz (8.1 %)",
        vatPurchase: "Reduzierter Satz (2.6 %)",
        sku: "456",
        barcode: "432",
        stock: "10",
        description: "This is a test product description 4."
    },
    {
        productName: "Salad",
        productVisibility: "Catalog",
        unit: "Kg",
        sellingPrice: "1400",
        purchasePrice: "1200",
        vatSale: "Export/Befreit (0 %)",
        vatPurchase: "Normalsatz (8.1 %)",
        sku: "567",
        barcode: "298",
        stock: "3",
        description: "This is a test product description 5."
    },
    {
        productName: "Greek Salad",
        productVisibility: "Search",
        unit: "cm",
        sellingPrice: "1500",
        purchasePrice: "1300",
        vatSale: "Reduzierter Satz (2.6 %)",
        vatPurchase: "Export/Befreit (0 %)",
        sku: "678",
        barcode: "105",
        stock: "2",
        description: "This is a test product description 6."
    },
    {
        productName: "Spaghetti Bolognese",
        productVisibility: "Catalog",
        unit: "g",
        sellingPrice: "1600",
        purchasePrice: "1400",
        vatSale: "Sondersatz (3.8 %)",
        vatPurchase: "Sondersatz (3.8 %)",
        sku: "789",
        barcode: "219",
        stock: "5",
        description: "This is a test product description 7."
    },
    {
        productName: "Alfredo",
        productVisibility: "Search",
        unit: "m",
        sellingPrice: "1700",
        purchasePrice: "1500",
        vatSale: "Normalsatz (8.1 %)",
        vatPurchase: "Reduzierter Satz (2.6 %)",
        sku: "900",
        barcode: "864",
        stock: "7",
        description: "This is a test product description 8."
    },
    {
        productName: "Grilled Salmon",
        productVisibility: "Catalog",
        unit: "ml",
        sellingPrice: "1800",
        purchasePrice: "1600",
        vatSale: "Export/Befreit (0 %)",
        vatPurchase: "Normalsatz (8.1 %)",
        sku: "011",
        barcode: "894",
        stock: "9",
        description: "This is a test product description 9."
    },
    {
        productName: "Chicken Tikka Masala",
        productVisibility: "Search",
        unit: "mm",
        sellingPrice: "1900",
        purchasePrice: "1700",
        vatSale: "Reduzierter Satz (2.6 %)",
        vatPurchase: "Export/Befreit (0 %)",
        sku: "122",
        barcode: "523",
        stock: "10",
        description: "This is a test product description 10."
    },
    {
        productName: "Sushi Platter",
        productVisibility: "Catalog",
        unit: "Stk",
        sellingPrice: "2000",
        purchasePrice: "1800",
        vatSale: "Sondersatz (3.8 %)",
        vatPurchase: "Sondersatz (3.8 %)",
        sku: "233",
        barcode: "590",
        stock: "3",
        description: "This is a test product description 11."
    },
    {
        productName: "Ramen Bowl",
        productVisibility: "Search",
        unit: "Kg",
        sellingPrice: "2100",
        purchasePrice: "1900",
        vatSale: "Normalsatz (8.1 %)",
        vatPurchase: "Reduzierter Satz (2.6 %)",
        sku: "344",
        barcode: "807",
        stock: "2",
        description: "This is a test product description 12."
    },
    {
        productName: "Tacos Al Pastor",
        productVisibility: "Catalog",
        unit: "cm",
        sellingPrice: "2200",
        purchasePrice: "2000",
        vatSale: "Export/Befreit (0 %)",
        vatPurchase: "Normalsatz (8.1 %)",
        sku: "455",
        barcode: "623",
        stock: "5",
        description: "This is a test product description 13."
    },
    {
        productName: "Burrito Bowl",
        productVisibility: "Search",
        unit: "g",
        sellingPrice: "2300",
        purchasePrice: "2100",
        vatSale: "Reduzierter Satz (2.6 %)",
        vatPurchase: "Export/Befreit (0 %)",
        sku: "566",
        barcode: "218",
        stock: "7",
        description: "This is a test product description 14."
    },
    {
        productName: "Fish and Chips",
        productVisibility: "Catalog",
        unit: "m",
        sellingPrice: "2400",
        purchasePrice: "2200",
        vatSale: "Sondersatz (3.8 %)",
        vatPurchase: "Sondersatz (3.8 %)",
        sku: "677",
        barcode: "132",
        stock: "9",
        description: "This is a test product description 15."
    },
    {
        productName: "Pad Thai",
        productVisibility: "Search",
        unit: "ml",
        sellingPrice: "2500",
        purchasePrice: "2300",
        vatSale: "Normalsatz (8.1 %)",
        vatPurchase: "Reduzierter Satz (2.6 %)",
        sku: "788",
        barcode: "230",
        stock: "10",
        description: "This is a test product description 16."
    },
    {
        productName: "Beef Steak",
        productVisibility: "Catalog",
        unit: "mm",
        sellingPrice: "2600",
        purchasePrice: "2400",
        vatSale: "Normalsatz (8.1 %)",
        vatPurchase: "Normalsatz (8.1 %)",
        sku: "899",
        barcode: "964",
        stock: "3",
        description: "This is a test product description 17."
    },
    {
        productName: "Lamb Kebab",
        productVisibility: "Search",
        unit: "Stk",
        sellingPrice: "2700",
        purchasePrice: "2500",
        vatSale: "Normalsatz (8.1 %)",
        vatPurchase: "Normalsatz (8.1 %)",
        sku: "010",
        barcode: "256",
        stock: "2",
        description: "This is a test product description 18."
    },
    {
        productName: "Chocolate Cake",
        productVisibility: "Catalog",
        unit: "Kg",
        sellingPrice: "2800",
        purchasePrice: "2600",
        vatSale: "Normalsatz (8.1 %)",
        vatPurchase: "Normalsatz (8.1 %)",
        sku: "121",
        barcode: "234",
        stock: "5",
        description: "This is a test product description 19."
    },
    {
        productName: "Apple Pie",
        productVisibility: "Search",
        unit: "cm",
        sellingPrice: "2900",
        purchasePrice: "2700",
        vatSale: "Normalsatz (8.1 %)",
        vatPurchase: "Normalsatz (8.1 %)",
        sku: "232",
        barcode: "679",
        stock: "7",
        description: "This is a test product description 20."
    }
];
